# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_Projecten/EindOpdracht1/Blokdesign/Blokdesign.srcs/sources_1/bd/design_1/ip/design_1_NeonIp_0_1/design_1_NeonIp_0_1.xci
# IP: The module: 'design_1_NeonIp_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projecten/EindOpdracht1/Blokdesign/Blokdesign.srcs/sources_1/bd/design_1/project_1/project_1.srcs/constrs_1/new/Neon.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_NeonIp_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Vivado_Projecten/EindOpdracht1/Blokdesign/Blokdesign.srcs/sources_1/bd/design_1/ip/design_1_NeonIp_0_1/design_1_NeonIp_0_1.xci
# IP: The module: 'design_1_NeonIp_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projecten/EindOpdracht1/Blokdesign/Blokdesign.srcs/sources_1/bd/design_1/project_1/project_1.srcs/constrs_1/new/Neon.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_NeonIp_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
