set_property IOSTANDARD LVCMOS33 [get_ports {outSeg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outSeg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outSeg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outSeg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outSeg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outSeg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outSeg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outSeg[0]}]

set_property PACKAGE_PIN N13 [get_ports {outSeg[7]}]
set_property PACKAGE_PIN N14 [get_ports {outSeg[6]}]
set_property PACKAGE_PIN K13 [get_ports {outSeg[5]}]
set_property PACKAGE_PIN L13 [get_ports {outSeg[4]}]
set_property PACKAGE_PIN L14 [get_ports {outSeg[3]}]
set_property PACKAGE_PIN M14 [get_ports {outSeg[2]}]
set_property PACKAGE_PIN L15 [get_ports {outSeg[1]}]
set_property PACKAGE_PIN M15 [get_ports {outSeg[0]}]
