set_property PACKAGE_PIN M15 [get_ports dout_0]
set_property PACKAGE_PIN K13 [get_ports sonar_echo_0]
set_property PACKAGE_PIN L15 [get_ports sonar_trig_0]
set_property IOSTANDARD LVCMOS18 [get_ports dout_0]
set_property IOSTANDARD LVCMOS18 [get_ports sonar_echo_0]
set_property IOSTANDARD LVCMOS18 [get_ports sonar_trig_0]
